"use client";

import { motion } from "framer-motion";
import { Code2, Download, CheckCircle2 } from "lucide-react";

export function CodeExport() {
  return (
    <section className="py-24 bg-brand-primary text-white overflow-hidden relative">
      {/* Background decoration */}
      <div className="absolute inset-0 bg-[url('https://transparenttextures.com/patterns/cubes.png')] opacity-10 mix-blend-overlay" />
      <div className="absolute -top-[20%] -right-[10%] w-[50%] h-[50%] bg-accent-pink/30 blur-[120px] rounded-full" />
      <div className="absolute -bottom-[20%] -left-[10%] w-[50%] h-[50%] bg-accent-teal/30 blur-[120px] rounded-full" />
      
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10 flex flex-col md:flex-row items-center gap-12">
        <div className="flex-1">
          <motion.div
            initial={{ opacity: 0, x: -30 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
          >
            <div className="inline-flex items-center px-3 py-1 rounded-full bg-white/10 border border-white/20 text-sm font-medium mb-6">
              <Code2 className="w-4 h-4 mr-2" /> No Vendor Lock-in
            </div>
            <h2 className="text-3xl md:text-5xl font-extrabold mb-6">
              Own your code. <br/>Export it anytime.
            </h2>
            <p className="text-lg text-white/80 mb-8 max-w-lg">
              We generate clean, production-ready Next.js and Prisma code. If you ever outgrow OneAtlas, you can click a button, download your entire source code repository, and host it anywhere you want.
            </p>
            
            <ul className="space-y-4 mb-8">
              {[
                "Clean Next.js 14 App Router code",
                "Standard Prisma ORM schemas",
                "TailwindCSS styling without obscure abstractions",
                "Full Git repository structure"
              ].map((feature, i) => (
                <li key={i} className="flex items-center text-white/90 font-medium">
                  <CheckCircle2 className="w-5 h-5 mr-3 text-accent-teal" />
                  {feature}
                </li>
              ))}
            </ul>

            <button className="px-6 py-3 bg-white text-brand-primary font-bold rounded-lg shadow-lg hover:bg-gray-100 transition-colors flex items-center group">
              <Download className="w-5 h-5 mr-2 group-hover:-translate-y-1 transition-transform" />
              View Sample Export
            </button>
          </motion.div>
        </div>

        <div className="flex-1 w-full">
          <motion.div
            initial={{ opacity: 0, x: 30 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5, delay: 0.2 }}
            className="bg-[#1A1B26] rounded-xl shadow-2xl overflow-hidden border border-white/10"
          >
            <div className="flex items-center px-4 py-3 border-b border-white/10 bg-[#16161E]">
              <div className="flex space-x-2">
                <div className="w-3 h-3 rounded-full bg-red-500" />
                <div className="w-3 h-3 rounded-full bg-yellow-500" />
                <div className="w-3 h-3 rounded-full bg-green-500" />
              </div>
              <span className="ml-4 text-xs font-mono text-gray-400">app/page.tsx - Exported Code</span>
            </div>
            <div className="p-6 text-sm font-mono overflow-x-auto text-gray-300">
              <pre>
                <code className="language-typescript">
{`import { db } from "@/lib/db";
import { DataTable } from "@/components/ui/data-table";

export default async function LeadsDashboard() {
  // Clean, native Prisma query generated by OneAtlas
  const leads = await db.lead.findMany({
    orderBy: { createdAt: "desc" },
    include: {
      assignedUser: true
    }
  });

  return (
    <div className="p-8">
      <h1 className="text-2xl font-bold mb-6">CRM Dashboard</h1>
      <DataTable data={leads} />
    </div>
  );
}`}
                </code>
              </pre>
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  );
}
